Response 규격 개발, JWT Utils Null or Empty 체크 수정
f-lab-edu/Apple-Market pull request #25
Opened 2022-08-13 13:51 UTC by xxxx-jeung

- 14일 내용 수정 예정

2022-08-16 02:40 UTC, f-lab-jason requested changes

2022-08-16 02:40 UTC, f-lab-jason commented on src/main/java/com/limited/sales/utils/HttpResponse.java
> +  private final int code;
Spring의 `HttpStatus`를 쓰는게 더 낫지않을까요?

2022-08-16 03:22 UTC, xxxx-jeung commented on src/main/java/com/limited/sales/utils/HttpResponse.java
> +  private final int code;
오! 오... 바로 작업하겠듭니다

2022-08-18 06:30 UTC, f-lab-jason approved these changes
🚢

2022-08-18 07:10 UTC, merged